; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MyApp"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "Cheukfung"
#define MyAppURL "https://github.com/Cheukfung"
#define MyAppExeName "entry.exe"
#define P "..\"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8A7DBC8E-5877-472D-86C5-F3D1F2DF3785}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
; LicenseFile="{#P}\resource\license.txt"
OutputDir="{#P}\release"
OutputBaseFilename="{#MyAppName}-v{#MyAppVersion}-installer"
SetupIconFile={#P}\resource\images\logo.ico
UninstallDisplayName=Uninstall {#MyAppName}
UninstallDisplayIcon={#P}\resource\images\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; 升级时自动沿用上次安装路径，并跳过目录选择页
DisableDirPage=auto
UsePreviousAppDir=yes
; 安装前尝试关闭正在运行的程序
CloseApplications=force
CloseApplicationsFilter=entry.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "{#P}\out\entry.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#P}\out\entry.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
