; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "剪辑助手"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "dragon"
#define MyAppURL "mailto:857134647@qq.com"
#define MyAppExeName "entry.exe"
#define P "..\"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8A7DBC8E-5877-472D-86C5-F3D1F2DF3785}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
; LicenseFile="{#P}\resource\license.txt"
OutputDir="{#P}\release"
OutputBaseFilename="{#MyAppName}-v{#MyAppVersion}-installer"
SetupIconFile={#P}\resource\images\logo.ico
UninstallDisplayName=卸载 {#MyAppName}
UninstallDisplayIcon={#P}\resource\images\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; 升级时自动沿用上次安装路径，并跳过目录选择页
DisableDirPage=auto
UsePreviousAppDir=yes
; 安装/升级前尽量关闭占用文件的进程（配合下方 [Code] 强制结束）
CloseApplications=force
CloseApplicationsFilter=entry.exe,ffmpeg.exe,ffprobe.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "{#P}\out\entry.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#P}\out\entry.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\卸载 {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function EscapeForPowerShellSingleQuoted(const S: String): String;
var
  I: Integer;
  Ch: Char;
begin
  Result := '';
  for I := 1 to Length(S) do
  begin
    Ch := S[I];
    if Ch = #39 then
      Result := Result + #39#39
    else
      Result := Result + Ch;
  end;
end;

procedure KillKnownExeNames;
var
  ResultCode: Integer;
begin
  { /T 结束整个进程树；忽略返回码（进程可能本就不存在） }
  Exec('taskkill.exe', '/F /IM entry.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM ffmpeg.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM ffprobe.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure KillProcessesUnderAppDir;
var
  ResultCode: Integer;
  AppDir, Escaped, Cmd: String;
begin
  AppDir := ExpandConstant('{app}');
  if AppDir = '' then
    Exit;
  { 去掉末尾反斜杠，便于 StartsWith 匹配 }
  if (Length(AppDir) > 3) and (AppDir[Length(AppDir)] = '\') then
    Delete(AppDir, Length(AppDir), 1);

  Escaped := EscapeForPowerShellSingleQuoted(AppDir);
  { 仅结束「可执行路径位于安装目录下」的进程，避免误杀用户自己的 Chrome }
  Cmd :=
    'Get-CimInstance Win32_Process | ' +
    'Where-Object { $_.ExecutablePath -and $_.ExecutablePath.StartsWith(''' + Escaped + ''', [StringComparison]::OrdinalIgnoreCase) } | ' +
    'ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }; ' +
    'Start-Sleep -Milliseconds 800';

  Exec(
    'powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "' + Cmd + '"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );
end;

procedure CloseAppRelatedProcesses;
begin
  KillKnownExeNames;
  KillProcessesUnderAppDir;
  { 再杀一次主程序进程树，确保释放 DLL/日志等占用 }
  KillKnownExeNames;
end;

function InitializeSetup(): Boolean;
begin
  { 安装目录尚未就绪，只能按进程名关闭 }
  KillKnownExeNames;
  Result := True;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  { 用户已确认安装目录后再按目录清理进程 }
  CloseAppRelatedProcesses;
  Result := '';
end;

function InitializeUninstall(): Boolean;
begin
  { 卸载前强制关闭，避免文件占用导致大量残留 }
  CloseAppRelatedProcesses;
  Result := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
    CloseAppRelatedProcesses;
end;
