; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "鍓緫鍔╂墜"
#define MyAppVersion "0.0.8"
#define MyAppPublisher "dragon"
#define MyAppURL "mailto:857134647@qq.com"
#define MyAppExeName "entry.exe"
#define P "..\"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8A7DBC8E-5877-472D-86C5-F3D1F2DF3785}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
; LicenseFile="{#P}\resource\license.txt"
OutputDir="{#P}\release"
OutputBaseFilename="{#MyAppName}-v{#MyAppVersion}-installer"
SetupIconFile={#P}\resource\images\logo.ico
UninstallDisplayName=鍗歌浇 {#MyAppName}
UninstallDisplayIcon={#P}\resource\images\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; 鍗囩骇鏃惰嚜鍔ㄦ部鐢ㄤ笂娆″畨瑁呰矾寰勶紝骞惰烦杩囩洰褰曢€夋嫨椤?
DisableDirPage=auto
UsePreviousAppDir=yes
; 瀹夎/鍗囩骇鍓嶅敖閲忓叧闂崰鐢ㄦ枃浠剁殑杩涚▼锛堥厤鍚堜笅鏂?[Code] 寮哄埗缁撴潫锛?
CloseApplications=force
CloseApplicationsFilter=entry.exe,ffmpeg.exe,ffprobe.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "{#P}\out\entry.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; 鎺掗櫎 config.json锛氬崌绾ф椂淇濈暀鐢ㄦ埛鏈湴閰嶇疆锛岄娆″畨瑁呭崟鐙啓鍏ュ共鍑€榛樿鏂囦欢
Source: "{#P}\out\entry.dist\*"; DestDir: "{app}"; Excludes: "config.json"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#P}\out\entry.dist\config.json"; DestDir: "{app}"; Flags: onlyifdoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\鍗歌浇 {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; 杩愯鏈熺敓鎴愮殑鏂囦欢锛坈onfig/logs/changdu_data/crash.log 绛夛級涓嶅湪瀹夎娓呭崟鍐咃紝闇€鏄惧紡娓呯悊
[UninstallDelete]
Type: filesandordirs; Name: "{app}\changdu_data"
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\__pycache__"
Type: files; Name: "{app}\config.json"
Type: files; Name: "{app}\crash.log"
Type: files; Name: "{app}\startup.log"
; 鍏滃簳锛氬垹闄ゅ畨瑁呯洰褰曚笅鍓╀綑鍏ㄩ儴鍐呭锛堝惈 Playwright 杩愯鏃ュ織绛夛級
Type: filesandordirs; Name: "{app}"

[Code]
function EscapeForPowerShellSingleQuoted(const S: String): String;
var
  I: Integer;
  Ch: Char;
begin
  Result := '';
  for I := 1 to Length(S) do
  begin
    Ch := S[I];
    if Ch = #39 then
      Result := Result + #39#39
    else
      Result := Result + Ch;
  end;
end;

procedure KillKnownExeNames;
var
  ResultCode: Integer;
begin
  { /T 缁撴潫鏁翠釜杩涚▼鏍戯紱蹇界暐杩斿洖鐮侊紙杩涚▼鍙兘鏈氨涓嶅瓨鍦級 }
  Exec('taskkill.exe', '/F /IM entry.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM ffmpeg.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM ffprobe.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure KillProcessesUnderAppDir;
var
  ResultCode: Integer;
  AppDir, Escaped, Cmd: String;
begin
  AppDir := ExpandConstant('{app}');
  if AppDir = '' then
    Exit;
  { 鍘绘帀鏈熬鍙嶆枩鏉狅紝渚夸簬 StartsWith 鍖归厤 }
  if (Length(AppDir) > 3) and (AppDir[Length(AppDir)] = '\') then
    Delete(AppDir, Length(AppDir), 1);

  Escaped := EscapeForPowerShellSingleQuoted(AppDir);
  { 浠呯粨鏉熴€屽彲鎵ц璺緞浣嶄簬瀹夎鐩綍涓嬨€嶇殑杩涚▼锛岄伩鍏嶈鏉€鐢ㄦ埛鑷繁鐨?Chrome }
  Cmd :=
    'Get-CimInstance Win32_Process | ' +
    'Where-Object { $_.ExecutablePath -and $_.ExecutablePath.StartsWith(''' + Escaped + ''', [StringComparison]::OrdinalIgnoreCase) } | ' +
    'ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }; ' +
    'Start-Sleep -Milliseconds 800';

  Exec(
    'powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "' + Cmd + '"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );
end;

procedure CloseAppRelatedProcesses;
begin
  KillKnownExeNames;
  KillProcessesUnderAppDir;
  { 鍐嶆潃涓€娆′富绋嬪簭杩涚▼鏍戯紝纭繚閲婃斁 DLL/鏃ュ織绛夊崰鐢?}
  KillKnownExeNames;
end;

function InitializeSetup(): Boolean;
begin
  { 瀹夎鐩綍灏氭湭灏辩华锛屽彧鑳芥寜杩涚▼鍚嶅叧闂?}
  KillKnownExeNames;
  Result := True;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  { 鐢ㄦ埛宸茬‘璁ゅ畨瑁呯洰褰曞悗鍐嶆寜鐩綍娓呯悊杩涚▼ }
  CloseAppRelatedProcesses;
  Result := '';
end;

function InitializeUninstall(): Boolean;
begin
  { 鍗歌浇鍓嶅己鍒跺叧闂紝閬垮厤鏂囦欢鍗犵敤瀵艰嚧澶ч噺娈嬬暀 }
  CloseAppRelatedProcesses;
  Result := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  AppDir: String;
begin
  if CurUninstallStep = usUninstall then
    CloseAppRelatedProcesses;
  { 鍗歌浇鏀跺熬鍐嶆竻涓€娆″畨瑁呯洰褰曪紝閬垮厤杩愯鏈熸柊寤烘枃浠舵畫鐣?}
  if CurUninstallStep = usPostUninstall then
  begin
    CloseAppRelatedProcesses;
    AppDir := ExpandConstant('{app}');
    if (AppDir <> '') and DirExists(AppDir) then
      DelTree(AppDir, True, True, True);
  end;
end;
